DESCRIPTION = "Watch state through a non-first stream: fresh watch, re-watch of a played movie, mark unplayed"


def run(t):
    movie = t.movie()
    row = t.row(movie)
    runtime = t.api.item(movie).get("RunTimeTicks") or 0
    t.check(runtime > 0, f"runtime {runtime}")
    pct = lambda p: int(runtime * p / 100)
    ud = lambda: t.api.user_data(movie)

    t.api.mark_played(movie, False)
    t.log("== fresh watch on row", row[:8])
    t.api.report("start", movie, row, 0)
    t.api.report("progress", movie, row, pct(30))
    m = ud()
    t.log("after progress 30%:", m, "| row:", t.api.user_data(row))
    t.equal(m["PlaybackPositionTicks"], pct(30), "movie position after progress")
    t.equal(m["Played"], False, "movie not played")
    resume = t.api.resume()
    t.check(movie in resume, "Continue Watching has the movie")
    t.check(row not in resume, "Continue Watching does not have the row")
    t.equal(t.api.sources(movie)[0], row, "the resumed stream is listed first")
    t.api.report("stop", movie, row, pct(35))
    t.equal(ud()["PlaybackPositionTicks"], pct(35), "movie position after stop")

    t.log("== re-watch after marking played")
    t.api.mark_played(movie, True)
    m = ud()
    t.check(m["Played"] and m["PlaybackPositionTicks"] == 0, "played, position reset")
    t.equal(t.api.user_data(row)["Played"], True, "row marked played with the movie")
    t.api.report("start", movie, row, 0)
    t.api.report("progress", movie, row, pct(30))
    m = ud()
    t.equal(m["PlaybackPositionTicks"], pct(30), "movie keeps the resume point while played")
    t.equal(m["Played"], True, "movie still played")
    t.api.report("progress", movie, row, pct(40))
    t.equal(ud()["PlaybackPositionTicks"], pct(40), "movie position after the second progress")
    t.api.report("stop", movie, row, pct(45))
    m = ud()
    t.equal(m["PlaybackPositionTicks"], pct(45), "movie position after stop")
    t.check(movie in t.api.resume() and row not in t.api.resume(), "Continue Watching has the movie only")

    t.log("== finish the movie on the row")
    t.api.report("start", movie, row, pct(45))
    t.api.report("stop", movie, row, pct(97))
    m = ud()
    t.check(m["Played"] and m["PlaybackPositionTicks"] == 0, f"movie played and reset after 97%: {m}")
    t.check(movie not in t.api.resume(), "Continue Watching drops the movie")

    t.log("== mark unplayed")
    t.api.mark_played(movie, False)
    m = ud()
    t.check(not m["Played"] and m["PlaybackPositionTicks"] == 0, f"movie unplayed: {m}")
    t.equal(t.api.user_data(row)["Played"], False, "row unplayed with the movie")
    t.check(movie not in t.api.resume(), "not in Continue Watching")
